### ISSUE TITLE
Be able to claim multiple balances at once

### ISSUE THREAD

**Issue by bjorn** [vinamogit/trezor-workaround#1]
Thanks for providing this useful tool!

Given the inconvenience of having to copy paste and sign two transactions each time, it would be nice if multiple claimable balances could be claimed at once.

Rather than displaying a list of radio boxes, the list would need to be changed to a list of checkboxes, ideally even with a "Claim everything" option.

**Comment by vinamogit** [comment]
Thank you for your contribution.
I created another branch for the github pages, so ui5 serve will work now from the main branch.
